export type WaveType = 'Reef Break' | 'Beach Break' | 'Point Break' | 'River Mouth' | 'Sand Bar'
export type Difficulty = 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert'
export type WslBadge = 'CT Stop' | 'Big Wave'

export interface Top100Spot {
  rank: number
  name: string
  locality: string
  country: string
  region: string
  lat: number
  lon: number
  waveType: WaveType
  difficulty: Difficulty
  bestSeason: string
  wslBadge?: WslBadge
  description: string
}

export const REGIONS = [
  'Hawaii',
  'North America',
  'Latin America',
  'Europe',
  'Africa & Atlantic',
  'Indian Ocean',
  'Southeast Asia',
  'Oceania & Pacific',
] as const

export type Region = typeof REGIONS[number]

export const SPOTS: Top100Spot[] = [
  // ── Hawaii ────────────────────────────────────────────────────────────────────
  {
    rank: 1,
    name: 'Banzai Pipeline',
    locality: 'North Shore, Oahu',
    country: 'USA',
    region: 'Hawaii',
    lat: 21.6651,
    lon: -158.0530,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Oct–Mar',
    wslBadge: 'CT Stop',
    description: 'The most iconic wave on earth, Pipeline throws a shattering left-hand barrel over a shallow coral reef on Oahu\'s North Shore. Six decades of surfing history have been defined here, from Gerry Lopez to Kelly Slater. When it\'s pumping at 8–12ft, it is simply the most thrilling and dangerous surf experience on the planet.',
  },
  {
    rank: 2,
    name: 'Sunset Beach',
    locality: 'North Shore, Oahu',
    country: 'USA',
    region: 'Hawaii',
    lat: 21.6782,
    lon: -158.0396,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Oct–Feb',
    wslBadge: 'CT Stop',
    description: 'A massive, complex reef break that tests every dimension of big-wave surfing. Sunset demands power, paddle fitness, and split-second decision-making as multiple peaks shift with each swell direction. At 15–20ft it becomes a relentless proving ground that has shaped every generation of Hawaiian big-wave surfing.',
  },
  {
    rank: 3,
    name: 'Waimea Bay',
    locality: 'North Shore, Oahu',
    country: 'USA',
    region: 'Hawaii',
    lat: 21.6428,
    lon: -158.0652,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Nov–Feb',
    wslBadge: 'Big Wave',
    description: 'The original big-wave arena, where Greg Noll paddled out in 1969 and modern big-wave surfing was born. Waimea only breaks on significant swells above 15ft and delivers thick, detonating drops into a deep bowl — requiring commitment at every level. The Bay\'s winter calm-to-chaos transformation is one of surfing\'s greatest spectacles.',
  },
  {
    rank: 4,
    name: 'Jaws (Pe\'ahi)',
    locality: 'Maui',
    country: 'USA',
    region: 'Hawaii',
    lat: 20.9399,
    lon: -156.3164,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Nov–Mar',
    wslBadge: 'Big Wave',
    description: 'Pe\'ahi — nicknamed Jaws — is the world\'s most dramatic open-ocean big-wave break, producing 60-80ft faces on Maui\'s north coast. Tow-in surfing was pioneered here in the early 1990s when paddle surfing became physically impossible at its scale. On the right winter swell it produces the most awe-inspiring imagery in all of surfing.',
  },
  {
    rank: 5,
    name: 'Honolua Bay',
    locality: 'Maui',
    country: 'USA',
    region: 'Hawaii',
    lat: 21.0188,
    lon: -156.6361,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Nov–Feb',
    wslBadge: 'CT Stop',
    description: 'A protected bay on Maui\'s northwest tip that funnels north swells into a long, perfectly shaped right-hand point. Honolua Bay is known for its crystal-clear water, its dramatic cliffs, and its ability to hold large winter surf with remarkable consistency. On a solid swell, the barrel sections rival anything in Hawaii.',
  },
  {
    rank: 6,
    name: 'Laniakea',
    locality: 'North Shore, Oahu',
    country: 'USA',
    region: 'Hawaii',
    lat: 21.6563,
    lon: -158.0585,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Oct–Mar',
    description: 'A classic North Shore right-hander that breaks over a broad reef with long, workable walls ideal for powerful surfing. Laniakea has been photographed and filmed more than almost any other North Shore break, and its reliable shape made it a proving ground for power surfing in the 1970s and 1980s. Sea turtles are common in the water.',
  },
  {
    rank: 7,
    name: 'Velzyland (V-Land)',
    locality: 'North Shore, Oahu',
    country: 'USA',
    region: 'Hawaii',
    lat: 21.6985,
    lon: -157.9930,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Nov–Feb',
    wslBadge: 'CT Stop',
    description: 'Tucked at the eastern end of the North Shore, V-Land is a shifty, powerful right that rewards the surfers willing to navigate its tricky paddle-out. Less crowded than Pipeline or Sunset, it has produced some of the most progressive North Shore surfing in recent decades. Deep-pit barrels in the right conditions make this a must-surf destination.',
  },
  {
    rank: 8,
    name: 'Haleiwa',
    locality: 'North Shore, Oahu',
    country: 'USA',
    region: 'Hawaii',
    lat: 21.5951,
    lon: -158.1052,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Oct–Mar',
    wslBadge: 'CT Stop',
    description: 'The town break and traditional opener of the North Shore Triple Crown. Haleiwa offers multiple peaks across a wide reef, handling everything from 3ft summer groundswells to 15ft winter pulses with equal grace. Its accessible channel and consistent shape have made it one of the most beloved all-round big-wave spots in Hawaii.',
  },

  // ── North America ──────────────────────────────────────────────────────────────
  {
    rank: 9,
    name: 'Mavericks',
    locality: 'Half Moon Bay, California',
    country: 'USA',
    region: 'North America',
    lat: 37.4913,
    lon: -122.5014,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Nov–Mar',
    wslBadge: 'Big Wave',
    description: 'The most ferocious big-wave spot in North America, Mavericks breaks over a submerged rock shelf a half-mile off the coast of Half Moon Bay. Thirty-foot faces, cold 55°F water, and a three-wave hold-down reputation make it one of the most demanding challenges in big-wave surfing. Mark Foo\'s death here in 1994 brought Mavericks global attention.',
  },
  {
    rank: 10,
    name: 'Trestles (Lowers)',
    locality: 'San Clemente, California',
    country: 'USA',
    region: 'North America',
    lat: 33.3862,
    lon: -117.5889,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Sep–Nov',
    wslBadge: 'CT Stop',
    description: 'Lowers at Trestles is California\'s most celebrated wave and a perennial CT venue, producing fast, punchy peaks over a sand-and-reef bottom inside a protected military base. The combination of consistent summer swells, warm water, and excellent shape has made it the proving ground for progressive surfing in the USA. No vehicles are allowed — you hike in past a river crossing.',
  },
  {
    rank: 11,
    name: 'Rincon Point',
    locality: 'Ventura, California',
    country: 'USA',
    region: 'North America',
    lat: 34.3700,
    lon: -119.4764,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Nov–Mar',
    description: 'Known as the "Queen of the Coast," Rincon is California\'s longest and most perfect point break, delivering classic right-hand walls from the Cobblestone all the way through the Rivermouth section. On a big NW swell you can ride 300 yards of flawless California wall. It set the template for what a perfect point break should be.',
  },
  {
    rank: 12,
    name: 'Blacks Beach',
    locality: 'San Diego, California',
    country: 'USA',
    region: 'North America',
    lat: 32.8820,
    lon: -117.2528,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Sep–Dec',
    description: 'A powerful, hollow beach break at the base of Torrey Pines cliffs, Blacks is reachable only by a steep path or a long paddle — a filter that keeps the crowd manageable. The shallow sandbar produces thick, punching barrels on NW swells that rival anything on the California coast. The clothing-optional beach adds to its counterculture mystique.',
  },
  {
    rank: 13,
    name: 'First Point Malibu',
    locality: 'Los Angeles, California',
    country: 'USA',
    region: 'North America',
    lat: 34.0365,
    lon: -118.6760,
    waveType: 'Point Break',
    difficulty: 'Intermediate',
    bestSeason: 'Sep–Nov',
    description: 'Where modern surfing culture was born. Malibu\'s First Point is a gentle, long-walling right that catalyzed the Gidget era and gave the world longboarding as we know it. Hopelessly crowded today but still produces some of the most photogenic, graceful rides on the California coast when a solid south or NW swell lines it up properly.',
  },
  {
    rank: 14,
    name: 'Steamer Lane',
    locality: 'Santa Cruz, California',
    country: 'USA',
    region: 'North America',
    lat: 36.9522,
    lon: -122.0275,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Oct–Mar',
    description: 'The soul of Northern California surfing, Steamer Lane is a network of reef breaks beneath the Santa Cruz cliffs that fires on NW winter swells. The Slot, Middle Peak, and Indicators offer distinct challenges — from grinding barrels to open-face walls — over a sharp limestone reef. Cold, powerful, and unforgiving, it is the West Coast equivalent of Ireland\'s reef breaks.',
  },
  {
    rank: 15,
    name: 'Huntington Beach Pier',
    locality: 'Huntington Beach, California',
    country: 'USA',
    region: 'North America',
    lat: 33.6553,
    lon: -118.0000,
    waveType: 'Beach Break',
    difficulty: 'Intermediate',
    bestSeason: 'Aug–Oct',
    wslBadge: 'CT Stop',
    description: 'Surf City USA is built around this pier break, which hosts the US Open of Surfing annually. The sandbars on both sides of the pier produce punchy, reliable peaks ideal for progressive surfing. Huntington\'s warm water, consistent summer south swells, and beach-city energy have made it the epicentre of mainstream American surf culture for 60 years.',
  },
  {
    rank: 16,
    name: 'Tofino',
    locality: 'British Columbia',
    country: 'Canada',
    region: 'North America',
    lat: 49.1513,
    lon: -125.9072,
    waveType: 'Beach Break',
    difficulty: 'Intermediate',
    bestSeason: 'Oct–Mar',
    description: 'The surf capital of Canada, Tofino sits on the wild west coast of Vancouver Island inside Pacific Rim National Park. Long Beach and Chesterman Beach face the open Pacific and catch powerful NW groundswells year-round. Surfing here means grey skies, old-growth forest, and bears on the beach — one of the world\'s most dramatic surf environments.',
  },
  {
    rank: 17,
    name: 'Cape Hatteras',
    locality: 'North Carolina',
    country: 'USA',
    region: 'North America',
    lat: 35.2516,
    lon: -75.5280,
    waveType: 'Beach Break',
    difficulty: 'Intermediate',
    bestSeason: 'Sep–Nov',
    description: 'The graveyard of the Atlantic is also one of the East Coast\'s best surf spots. The collision of the Gulf Stream and the Labrador Current creates constantly shifting sandbars that produce quality beach break waves. Hurricane season delivers long-period groundswells that travel the length of the Atlantic, and the National Seashore protects miles of unspoiled beach.',
  },
  {
    rank: 18,
    name: 'Sebastian Inlet',
    locality: 'Melbourne, Florida',
    country: 'USA',
    region: 'North America',
    lat: 27.8587,
    lon: -80.4498,
    waveType: 'Reef Break',
    difficulty: 'Intermediate',
    bestSeason: 'Sep–Feb',
    description: 'The best surf break on Florida\'s Space Coast and the wave that produced Kelly Slater and CJ Hobgood. The First Peak at Sebastian Inlet draws energy from a tidal jetty, creating a consistent, punchy right-hander that has produced more professional surfers per square mile than almost any other spot in the USA. Shark sightings are part of the deal.',
  },

  // ── Latin America ──────────────────────────────────────────────────────────────
  {
    rank: 19,
    name: 'Puerto Escondido (Zicatela)',
    locality: 'Oaxaca',
    country: 'Mexico',
    region: 'Latin America',
    lat: 15.8669,
    lon: -97.0716,
    waveType: 'Beach Break',
    difficulty: 'Expert',
    bestSeason: 'May–Oct',
    description: 'The Mexican Pipeline is one of the most powerful beach breaks on the planet, driven by long-period South Pacific groundswells that detonate on a steep sand bottom with little warning. At 8–12ft it produces some of the most violent barrels in the world, and the shore break alone has been responsible for serious injury. The town of Puerto Escondido has built its entire identity around this wave.',
  },
  {
    rank: 20,
    name: 'Killers (Todos Santos Island)',
    locality: 'Baja California',
    country: 'Mexico',
    region: 'Latin America',
    lat: 29.0000,
    lon: -118.3167,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Nov–Mar',
    wslBadge: 'Big Wave',
    description: 'Forty-five miles west of Ensenada in the Pacific, Todos Santos Island hosts Killers — a massive reef break capable of producing 50ft+ faces when large NW swells march south. It was the site of the Todos Santos Challenge big-wave contest and launched the careers of Mexican big-wave surfers. Reaching it requires a boat ride through cold, open ocean.',
  },
  {
    rank: 21,
    name: 'Punta de Mita',
    locality: 'Nayarit',
    country: 'Mexico',
    region: 'Latin America',
    lat: 20.7667,
    lon: -105.5333,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'May–Sep',
    description: 'A picturesque point on Mexico\'s Riviera Nayarit that breaks over a shallow reef on summer South Pacific swells. The wave at La Lancha and The Cove offers long, workable walls for powerful surfing in warm, clear water with backdrop views of the Sierra Madre. The upscale resort town has gentrified the area, but the surf remains world-class.',
  },
  {
    rank: 22,
    name: 'Pascuales',
    locality: 'Colima',
    country: 'Mexico',
    region: 'Latin America',
    lat: 18.7500,
    lon: -103.8167,
    waveType: 'Beach Break',
    difficulty: 'Expert',
    bestSeason: 'Jun–Sep',
    description: 'An isolated, brutal beach break on Mexico\'s Pacific coast that fires on summer SW swells directed from storms in the southern hemisphere. Pascuales is relatively unknown outside of Mexico but produces some of the most powerful, barreling beach break waves in the Americas — arriving without warning and closing out with immense force over a shallow sand bottom.',
  },
  {
    rank: 23,
    name: 'Witch\'s Rock (Roca Bruja)',
    locality: 'Guanacaste',
    country: 'Costa Rica',
    region: 'Latin America',
    lat: 10.9350,
    lon: -85.8753,
    waveType: 'Beach Break',
    difficulty: 'Advanced',
    bestSeason: 'May–Nov',
    description: 'A remote beach break inside Santa Rosa National Park, accessible only by 4WD track or boat. Witch\'s Rock delivers powerful, hollow lefts and rights on NW and SW swells over a sand bottom backed by volcanic rock formations. The isolation keeps the crowd small, the wildlife abundant, and the surf experience genuinely raw. Howler monkeys are your alarm clock.',
  },
  {
    rank: 24,
    name: 'Salsa Brava',
    locality: 'Puerto Viejo',
    country: 'Costa Rica',
    region: 'Latin America',
    lat: 9.6556,
    lon: -82.7180,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Dec–Mar',
    description: 'A heavy Caribbean reef break that produces thick, shallow-water barrels over a sharp coral shelf. Salsa Brava is the most powerful wave on the Caribbean side of Central America, driven by North Atlantic swells that funnel through the Lesser Antilles. The shallow reef and the violence of the barrel make it a place where you earn your tube rides.',
  },
  {
    rank: 25,
    name: 'El Tunco',
    locality: 'La Libertad',
    country: 'El Salvador',
    region: 'Latin America',
    lat: 13.5001,
    lon: -89.3875,
    waveType: 'Beach Break',
    difficulty: 'Intermediate',
    bestSeason: 'Nov–Apr',
    description: 'El Salvador\'s most visited surf village clusters around a black-sand beach and volcanic rock point that catches almost every Pacific swell. El Tunco is famous for its consistent surf, warm water year-round, and the lively beach-town scene that has made it a hub for the Central American surf community. Great for intermediate surfers with beginner-friendly whitewater on smaller days.',
  },
  {
    rank: 26,
    name: 'Punta Roca',
    locality: 'La Libertad',
    country: 'El Salvador',
    region: 'Latin America',
    lat: 13.4908,
    lon: -89.3758,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Nov–Apr',
    description: 'A long, fast right-hand point that has driven El Salvador\'s rise as a surf destination. Punta Roca wraps swell around a rocky headland to produce walls that run 200–300m, rewarding surfers who can read the line-up and surf at speed. The wave has hosted international competitions and represents the best of what El Salvador\'s Pacific coast can offer.',
  },
  {
    rank: 27,
    name: 'Chicama',
    locality: 'La Libertad, La Libertad Region',
    country: 'Peru',
    region: 'Latin America',
    lat: -7.8467,
    lon: -79.4498,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Apr–Oct',
    description: 'The longest rideable left-hand wave in the world, Chicama wraps around a peninsula in northern Peru for up to four kilometres on the right swell. A single ride can last four to six minutes across the Malabrigo, Punto, Keys, and El Hombre sections. Cold Humboldt Current water (around 17°C) keeps crowds thin and the wave virtually perfect on winter groundswells.',
  },
  {
    rank: 28,
    name: 'Punta Hermosa',
    locality: 'Lima',
    country: 'Peru',
    region: 'Latin America',
    lat: -12.3500,
    lon: -76.9667,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Apr–Oct',
    description: 'Lima\'s premier surf spot, Punta Hermosa hosts multiple breaks — Señoritas, Caballeros, and Slabs — that deliver quality left and right-handers on the Humboldt Current swells. The area is the centre of Peruvian competitive surfing and has produced WSL-level athletes. Cold water and long winter groundswells are the price of entry for some of South America\'s best waves.',
  },
  {
    rank: 29,
    name: 'Pico Alto',
    locality: 'Lima',
    country: 'Peru',
    region: 'Latin America',
    lat: -12.4000,
    lon: -77.0167,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Apr–Sep',
    wslBadge: 'Big Wave',
    description: 'Peru\'s big-wave capital breaks over a deep-water reef just offshore from Punta Hermosa. Pico Alto is capable of producing 30–40ft faces on the right Humboldt Current groundswell, and has been the site of Peru\'s big-wave challenge. Cold water, complex currents, and explosive size make it one of the most challenging big-wave venues in the Southern Hemisphere.',
  },
  {
    rank: 30,
    name: 'Arica',
    locality: 'Arica and Parinacota',
    country: 'Chile',
    region: 'Latin America',
    lat: -18.4783,
    lon: -70.3126,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Apr–Sep',
    description: 'Chile\'s northernmost city sits at the foot of the Atacama Desert and faces a left-hand point break that fires on long-period South Pacific swells. Arica has hosted ISA World Surfing Games and delivered Chile\'s first world champions. The wave breaks over a cobblestone and sand bottom with a backdrop of the Morro de Arica cliff — one of the world\'s most photogenic surf settings.',
  },

  // ── Europe ────────────────────────────────────────────────────────────────────
  {
    rank: 31,
    name: 'Nazaré',
    locality: 'Centro',
    country: 'Portugal',
    region: 'Europe',
    lat: 39.6014,
    lon: -9.0716,
    waveType: 'Beach Break',
    difficulty: 'Expert',
    bestSeason: 'Oct–Mar',
    wslBadge: 'Big Wave',
    description: 'Home to the biggest waves ever surfed. A submarine canyon focuses Atlantic swells into a wall of water in front of the Praia do Norte that can exceed 100ft. Rodrigo Koxa and Garrett McNamara both set world records here. The canyon amplifies already large Atlantic storms into something that defies comprehension — and yet surfers paddle into it.',
  },
  {
    rank: 32,
    name: 'Supertubos',
    locality: 'Peniche',
    country: 'Portugal',
    region: 'Europe',
    lat: 39.3654,
    lon: -9.4078,
    waveType: 'Beach Break',
    difficulty: 'Expert',
    bestSeason: 'Sep–Mar',
    wslBadge: 'CT Stop',
    description: 'Europe\'s Pipeline, Supertubos is a thick, powerful beach break on a sand bottom that produces barreling waves of extraordinary quality on Atlantic swells. The CT Rip Curl Pro Portugal has been held here for decades and regularly produces the highest scores of any European event. Cold water, heavy lips, and shallow sand make it genuinely dangerous at size.',
  },
  {
    rank: 33,
    name: 'Ribeira d\'Ilhas',
    locality: 'Ericeira',
    country: 'Portugal',
    region: 'Europe',
    lat: 39.2833,
    lon: -9.3883,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Sep–Apr',
    description: 'The centrepiece of the Ericeira World Surfing Reserve, Ribeira d\'Ilhas is a long, shapely right-hand point that handles a wide range of swell sizes with elegance. The Reserve spans 4km of coastline with multiple world-class breaks. Ribeira d\'Ilhas is the most consistent, accessible wave in the Reserve — a perfect expression of European Atlantic point break surfing.',
  },
  {
    rank: 34,
    name: 'Coxos',
    locality: 'Ericeira',
    country: 'Portugal',
    region: 'Europe',
    lat: 38.9963,
    lon: -9.4164,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Oct–Mar',
    description: 'The most revered reef in Europe, Coxos is a long right-hand barrel that tracks along a ledge of rock inside the Ericeira Reserve. Only breaking at size, Coxos rewards the patient with some of the most spectacular barrel sections in the Atlantic — long, fast, and genuinely dangerous when the swell tops 8ft. It is to Europe what Backdoor is to Pipeline.',
  },
  {
    rank: 35,
    name: 'Mundaka',
    locality: 'Basque Country',
    country: 'Spain',
    region: 'Europe',
    lat: 43.4072,
    lon: -2.6983,
    waveType: 'River Mouth',
    difficulty: 'Expert',
    bestSeason: 'Sep–Mar',
    wslBadge: 'CT Stop',
    description: 'Europe\'s most famous left-hand barrel, Mundaka is a sand-bottom river mouth break in the Basque Country that forms when Atlantic swells combine with outgoing river currents. The result is a cavernous, tube-heavy left that can run 400 metres on the best days. Dredging and sand loss have affected it in recent decades, but when it works, there is nothing else like it in Europe.',
  },
  {
    rank: 36,
    name: 'El Quemao',
    locality: 'Lanzarote',
    country: 'Spain',
    region: 'Europe',
    lat: 29.0638,
    lon: -13.6222,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Oct–Mar',
    description: 'A heavy left-hand slab on the west coast of Lanzarote that detonates over a shallow lava reef with virtually no warning. El Quemao is Canary Islands surfing at its most raw — cold upwellings, Atlantic fetch, and a reef that breaks bones. In the right conditions it produces some of the best barrels in Spain, with a committed local crew that guards it closely.',
  },
  {
    rank: 37,
    name: 'La Gravière',
    locality: 'Hossegor',
    country: 'France',
    region: 'Europe',
    lat: 43.6667,
    lon: -1.4333,
    waveType: 'Beach Break',
    difficulty: 'Expert',
    bestSeason: 'Sep–Nov',
    wslBadge: 'CT Stop',
    description: 'The finest beach break in Europe and the venue for the Quiksilver Pro France. La Gravière\'s famous sandy bottom creates barreling peaks that rival anything in the world when the Atlantic delivers proper autumn swells. The whole Hossegor stretch — from La Nord to Les Culs Nuls — produces waves of consistent, exceptional quality throughout the long surf season.',
  },
  {
    rank: 38,
    name: 'La Norte',
    locality: 'Hossegor',
    country: 'France',
    region: 'Europe',
    lat: 43.6800,
    lon: -1.4500,
    waveType: 'Beach Break',
    difficulty: 'Expert',
    bestSeason: 'Sep–Nov',
    description: 'Just north of La Gravière, La Norte handles the largest Atlantic swells that hit the Hossegor coast and transforms them into powerful, cavernous barrels. When the swell is too big for La Gravière, the tour moves here. The banks shift seasonally, but the quality of the wave when it lines up is consistently among the best beach break surfing anywhere in the world.',
  },
  {
    rank: 39,
    name: 'Pantín',
    locality: 'Galicia',
    country: 'Spain',
    region: 'Europe',
    lat: 43.6394,
    lon: -7.9997,
    waveType: 'Beach Break',
    difficulty: 'Advanced',
    bestSeason: 'Sep–Nov',
    description: 'A large, exposed beach on Spain\'s wild Atlantic coast that has hosted the Pantín Classic since 1988. Galicia\'s green headlands and Atlantic swells combine to produce powerful, consistent beach break surfing in a spectacular setting. The contest site has attracted every major professional surfer over three decades, and the town treats surf culture as a cornerstone of its identity.',
  },
  {
    rank: 40,
    name: 'Fistral Beach',
    locality: 'Newquay, Cornwall',
    country: 'UK',
    region: 'Europe',
    lat: 50.4117,
    lon: -5.0883,
    waveType: 'Beach Break',
    difficulty: 'Intermediate',
    bestSeason: 'Sep–Mar',
    description: 'The most famous surf beach in Britain and the headquarters of the UK surf industry. Fistral faces the open Atlantic and catches swells from the NW and SW with impressive regularity. The Boardmasters Festival here is Europe\'s largest surf event. Cold water and variable conditions are the reality, but on a proper Atlantic swell it delivers quality beach break surfing.',
  },
  {
    rank: 41,
    name: 'Thurso East',
    locality: 'Caithness, Scotland',
    country: 'UK',
    region: 'Europe',
    lat: 58.5936,
    lon: -3.5220,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Sep–Mar',
    description: 'The most northerly CT-quality wave in the world, Thurso East is a slab reef break on the north coast of Scotland that produces thick, powerful right-handers on North Atlantic swells. It has hosted the O\'Neill Highland Open and introduced the world to Scottish surfing. Surfing here in December means two hours of daylight, 7°C water, and waves that could be on a Brazilian postcard.',
  },
  {
    rank: 42,
    name: 'Mullaghmore Head',
    locality: 'County Sligo',
    country: 'Ireland',
    region: 'Europe',
    lat: 54.4700,
    lon: -8.4600,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Nov–Mar',
    wslBadge: 'Big Wave',
    description: 'Ireland\'s most powerful and consequential big-wave venue, Mullaghmore is a left-hand slab that jacks up on a submerged reef and delivers 40ft-plus faces on monster North Atlantic storms. Conor Maguire and Ollie O\'Flaherty have pushed Irish big-wave surfing to global recognition here. A medieval castle on the headland provides the world\'s most cinematic backdrop.',
  },
  {
    rank: 43,
    name: 'Crab Island',
    locality: 'County Donegal',
    country: 'Ireland',
    region: 'Europe',
    lat: 54.6180,
    lon: -8.7700,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Nov–Mar',
    wslBadge: 'Big Wave',
    description: 'A chunky, shallow slab tucked off the coast of Donegal that only comes alive on the largest Atlantic swells. Crab Island is part of Ireland\'s emerging big-wave scene, producing thick, heavy barrels that hold up surprisingly well at size. The lineup requires a boat or a long paddle in treacherous conditions — adding another layer of commitment to an already demanding wave.',
  },
  {
    rank: 44,
    name: 'Bundoran',
    locality: 'County Donegal',
    country: 'Ireland',
    region: 'Europe',
    lat: 54.4790,
    lon: -8.2840,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Oct–Mar',
    description: 'The surf capital of Ireland is a small seaside town in Donegal that draws Atlantic swells onto a series of reef breaks around the headland. The Peak at Bundoran is a perfectly formed A-frame that breaks left and right with consistency and power. The town has built a thriving surf economy around its breaks, and the local surf culture is among the most passionate in Europe.',
  },

  // ── Africa & Atlantic ──────────────────────────────────────────────────────────
  {
    rank: 45,
    name: 'Jeffreys Bay',
    locality: 'Eastern Cape',
    country: 'South Africa',
    region: 'Africa & Atlantic',
    lat: -34.0530,
    lon: 24.9200,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Jun–Aug',
    wslBadge: 'CT Stop',
    description: 'The fastest, longest right-hand point break in the world. J-Bay runs from Boneyards through Supertubes, Impossibles, and Kitchen Windows for up to 800 metres of wall-to-wall perfection. The CT stop here annually produces the highest aggregate scores in surfing. Cold Benguela Current water and offshore SW winds keep conditions precise and the experience unlike anywhere else on earth.',
  },
  {
    rank: 46,
    name: 'Skeleton Bay',
    locality: 'Skeleton Coast',
    country: 'Namibia',
    region: 'Africa & Atlantic',
    lat: -22.8667,
    lon: 14.4833,
    waveType: 'Sand Bar',
    difficulty: 'Expert',
    bestSeason: 'Mar–Sep',
    description: 'The world\'s longest sand-bottom left-hand barrel, Skeleton Bay runs for 1–2 kilometres over a moving desert sandbar in one of the most desolate coastlines on earth. Discovered by the wider surfing world around 2008, it produces tube rides that last several minutes — unheard of anywhere else. Cold water (12°C), great white sharks, and howling Benguela winds are part of every session.',
  },
  {
    rank: 47,
    name: 'Anchor Point',
    locality: 'Taghazout, Agadir',
    country: 'Morocco',
    region: 'Africa & Atlantic',
    lat: 30.4220,
    lon: -9.6340,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Oct–Mar',
    description: 'Morocco\'s flagship wave is a long right-hander that peels along a rocky point north of Agadir on Atlantic groundswells. Anchor Point offers rides of up to 400 metres — plenty of time for powerful surfing on a consistent wall. The Atlas Mountains form the backdrop, the water is cold and clear, and the Moroccan surf culture that has grown around Taghazout village is warm and welcoming.',
  },
  {
    rank: 48,
    name: 'Killer Point',
    locality: 'Taghazout, Agadir',
    country: 'Morocco',
    region: 'Africa & Atlantic',
    lat: 30.3950,
    lon: -9.6200,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Oct–Mar',
    description: 'Just south of Anchor Point, Killer Point is a longer, more exposed right that only comes alive on the biggest Atlantic swells. When it fires, it delivers one of the longest point break rides in Morocco — grinding along a rocky coastline for 500+ metres. The two breaks rarely peak on the same day, making the choice between them one of the great tactical decisions of a Moroccan surf trip.',
  },
  {
    rank: 49,
    name: 'Cape St. Francis',
    locality: 'Eastern Cape',
    country: 'South Africa',
    region: 'Africa & Atlantic',
    lat: -34.1950,
    lon: 24.8370,
    waveType: 'Point Break',
    difficulty: 'Intermediate',
    bestSeason: 'May–Sep',
    description: 'The mythical "perfect wave" that inspired the 1966 surf film *The Endless Summer*, Cape St. Francis is a long right-hand point that works on the same Indian Ocean swells as Jeffreys Bay. It is more fickle and rarely as powerful as J-Bay, but on the right day it delivers the kind of long, elegant rides that Bruce Brown captured on 16mm and showed the world. The romance around this wave is indestructible.',
  },
  {
    rank: 50,
    name: 'Phantom Forest',
    locality: 'Cape Town',
    country: 'South Africa',
    region: 'Africa & Atlantic',
    lat: -34.1090,
    lon: 18.3960,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Apr–Sep',
    description: 'One of Cape Town\'s most secretive reef breaks, Phantom Forest fires on solid SW Atlantic swells to produce a thick, powerful right-hand barrel in cold, shark-heavy waters. The Cape Peninsula\'s dramatic mountains rise behind the break, and the combination of heavy surf and genuine wilderness makes every session here feel consequential. Crowd levels stay low by necessity.',
  },
  {
    rank: 51,
    name: 'Taghazout',
    locality: 'Souss-Massa',
    country: 'Morocco',
    region: 'Africa & Atlantic',
    lat: 30.5378,
    lon: -9.7086,
    waveType: 'Point Break',
    difficulty: 'Intermediate',
    bestSeason: 'Oct–Mar',
    description: 'A charming fishing village that has become Morocco\'s surf hub, Taghazout itself faces a right-hand point that catches mid-size Atlantic swells and delivers fun, accessible waves in front of the brightly painted houses. It\'s the perfect base camp for the cluster of world-class waves — Hash Point, Panoramas, Mysteries — that spread north along the coast.',
  },
  {
    rank: 52,
    name: 'El Médano',
    locality: 'Tenerife',
    country: 'Spain',
    region: 'Africa & Atlantic',
    lat: 28.0510,
    lon: -16.5330,
    waveType: 'Beach Break',
    difficulty: 'Intermediate',
    bestSeason: 'Nov–Mar',
    description: 'Tenerife\'s south coast beach town faces unimpeded North Atlantic swells and consistent Alisio trade winds that make El Médano one of the world\'s premier windsurfing and kiteboarding destinations. On glassy mornings, however, the beach break delivers solid surf for all levels. The Canary Islands\' year-round warm-ish water and excellent swell exposure keep it on every European surfer\'s travel list.',
  },

  // ── Indian Ocean ───────────────────────────────────────────────────────────────
  {
    rank: 53,
    name: 'Pasta Point',
    locality: 'North Malé Atoll',
    country: 'Maldives',
    region: 'Indian Ocean',
    lat: 4.6333,
    lon: 73.5000,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Mar–Oct',
    description: 'The most celebrated wave in the Maldives, Pasta Point is a long left-hand reef break that works on Indian Ocean swells with clockwork consistency. Accessible only to guests of the adjacent Cinnamon Dhonveli resort, it offers exclusivity and quality in equal measure. The wave holds up to 6ft with classic tube sections, set against the turquoise water and white sand of a perfect atoll.',
  },
  {
    rank: 54,
    name: 'Sultans',
    locality: 'South Malé Atoll',
    country: 'Maldives',
    region: 'Indian Ocean',
    lat: 4.1750,
    lon: 73.5167,
    waveType: 'Reef Break',
    difficulty: 'Intermediate',
    bestSeason: 'Mar–Oct',
    description: 'The most accessible and consistent wave in the Maldives surf zone, Sultans is a long, fun right-hander that breaks on the outside of the atoll and delivers playful, workable walls for surfers of intermediate and above ability. The boat-access lineup, crystal-clear warm water, and consistent swell direction from the Indian Ocean make it the go-to wave for surf charters in the region.',
  },
  {
    rank: 55,
    name: 'Desert Point',
    locality: 'Lombok',
    country: 'Indonesia',
    region: 'Indian Ocean',
    lat: -8.7500,
    lon: 115.8667,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'May–Oct',
    description: 'Widely regarded as one of the longest and most perfect barrels in the world, Desert Point is a left-hand reef break in a remote bay on the southwest tip of Lombok. When the dry season swells arrive from the southern Indian Ocean, it produces cavernous, draining barrels that run for hundreds of metres with barely a section to interrupt the ride. The isolation and perfection create a kind of surfing pilgrimage.',
  },
  {
    rank: 56,
    name: 'G-Land (Grajagan)',
    locality: 'East Java',
    country: 'Indonesia',
    region: 'Indian Ocean',
    lat: -8.6000,
    lon: 114.3333,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Jun–Sep',
    description: 'Deep in the Alas Purwo National Park on Java\'s remote southeastern tip, G-Land is one of the original Indonesian surf discoveries — a left-hand point that fires on Indian Ocean groundswells across multiple sections (Kongs, Money Trees, Launching Pads). Surf camps in the jungle have operated here since the 1970s. The waves are powerful, the jungle is dense, and the monkeys steal everything.',
  },
  {
    rank: 57,
    name: 'Salani',
    locality: 'Upolu Island',
    country: 'Samoa',
    region: 'Indian Ocean',
    lat: -14.0750,
    lon: -171.5833,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'May–Oct',
    description: 'A world-class left-hand reef break on the south coast of Samoa\'s main island that delivers long, powerful barrels in a genuinely remote Pacific setting. Salani works on south swells that travel from the roaring forties without obstruction, producing waves of outstanding consistency and power. The local village community is an integral part of the experience here.',
  },
  {
    rank: 58,
    name: 'Ha\'atafu Beach',
    locality: 'Tongatapu',
    country: 'Tonga',
    region: 'Indian Ocean',
    lat: -21.1167,
    lon: -175.3833,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Jun–Sep',
    description: 'On the northwestern tip of Tongatapu, Ha\'atafu faces open Pacific swells and offers a variety of reef breaks for intermediate to expert surfers. The beach faces north and catches winter swells with good consistency. The combination of warm Pacific water, uncrowded lineup, and the raw beauty of Tonga\'s islands makes this one of the South Pacific\'s most rewarding off-the-beaten-path surf destinations.',
  },

  // ── Southeast Asia ─────────────────────────────────────────────────────────────
  {
    rank: 59,
    name: 'Uluwatu',
    locality: 'Bukit Peninsula, Bali',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -8.8294,
    lon: 115.0846,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Apr–Oct',
    wslBadge: 'CT Stop',
    description: 'The most iconic surf break in Bali, Uluwatu is a long left-hand reef break accessed through a cave in a cliff face beneath a Hindu temple. Multiple sections — The Peak, Racetrack, and Outside Corner — produce rides of 200–300m on solid Indian Ocean swells. The temple, the cliffs, the monkeys, and the wave itself make Uluwatu the complete tropical surf experience.',
  },
  {
    rank: 60,
    name: 'Padang Padang',
    locality: 'Bukit Peninsula, Bali',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -8.8118,
    lon: 115.0876,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'May–Sep',
    wslBadge: 'CT Stop',
    description: 'Bali\'s Padang Padang is a short, ferociously shallow barrel that breaks directly at the base of limestone cliffs over a razor-sharp reef. It only works on the biggest Indian Ocean swells but when it fires, it produces some of the most extreme tube surfing in the world. The CT Rip Curl Cup has been held here on invitation — waiting, sometimes for years, for the right swell.',
  },
  {
    rank: 61,
    name: 'Keramas',
    locality: 'Gianyar, Bali',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -8.6786,
    lon: 115.3066,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Apr–Oct',
    description: 'A powerful right-hand reef break on Bali\'s east coast that fires on SE swells and has recently hosted the CT Komune Bali Pro. Keramas produces punchy, fast barrels that have attracted some of the world\'s best surfers to train here. The wave works on all tides, and night surfing sessions under floodlights have given it a spectacle no other Indonesian break can match.',
  },
  {
    rank: 62,
    name: 'Medewi',
    locality: 'West Bali',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -8.4081,
    lon: 114.9233,
    waveType: 'Point Break',
    difficulty: 'Intermediate',
    bestSeason: 'Apr–Oct',
    description: 'Bali\'s longest left-hand point break peels along a cobblestone and lava reef on the island\'s quiet western coast. Medewi is Bali\'s answer to Rincon — gentle enough for intermediate surfers on smaller days, yet holding shape at 6ft and delivering long, satisfying rides. The village atmosphere is relaxed and removed from the Bukit\'s tourist circus.',
  },
  {
    rank: 63,
    name: 'Lance\'s Right (HTs)',
    locality: 'Mentawai Islands',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -2.6833,
    lon: 99.5667,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Apr–Oct',
    description: 'The most photographed wave in the Mentawai Islands and one of the most perfect right-hand barrels anywhere on earth. Lance\'s Right (also known as HTs) is a long, draining tube that runs over a coral reef with machine-like precision on Indian Ocean groundswells. Every surfer who has ridden it considers it a life-defining experience. Access is by liveaboard only.',
  },
  {
    rank: 64,
    name: 'Macaronis',
    locality: 'Mentawai Islands',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -2.3500,
    lon: 99.5500,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Apr–Oct',
    description: 'A fun, consistent left-hand reef break in the southern Mentawais that offers big barrels with slightly more room for error than the heavier breaks. Macaronis is beloved for its consistency — it\'s almost always surfable — and its perfectly shaped barrel sections that allow even solid intermediate surfers to get tubed. The Mentawai liveaboard circuit typically includes it on every itinerary.',
  },
  {
    rank: 65,
    name: 'Telescopes',
    locality: 'Mentawai Islands',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -2.8333,
    lon: 99.5833,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Apr–Oct',
    description: 'A dreamy right-hand reef break in the Mentawais that catches a wide range of swell sizes and delivers long, peeling barrels with an aesthetic quality rarely matched. Telescopes is the Mentawai break most likely to appear on magazine covers — the water is impossibly clear, the barrel is perfectly round, and the channel provides an easy paddle-out. One of the most purely beautiful surf spots on earth.',
  },
  {
    rank: 66,
    name: 'Nias (Sorake Bay)',
    locality: 'North Sumatra',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: 0.6833,
    lon: 97.7333,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Jun–Sep',
    description: 'One of the original discoveries of the Indonesian surf exodus in the 1970s, Nias breaks over a coral reef on the island\'s south coast to deliver thick, powerful rights. At size it rivals anything in the Mentawais — long, draining barrels over a shallow reef with genuine consequence. The 2004 tsunami destroyed much of the island but the wave, raised slightly by tectonic activity, recovered beautifully.',
  },
  {
    rank: 67,
    name: 'Cloud 9',
    locality: 'Siargao Island',
    country: 'Philippines',
    region: 'Southeast Asia',
    lat: 9.8315,
    lon: 126.1009,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Sep–Dec',
    wslBadge: 'CT Stop',
    description: 'The most famous wave in the Philippines and the host of the CT Siargao Cloud 9 Surfing Cup. Cloud 9 is a hollow right-hand reef break that jacks up over a shallow mushroom coral shelf and delivers explosive barrels when the northeast monsoon brings consistent groundswells. The iconic wooden viewing platform overlooking the break has made it one of the most recognisable images in Asian surfing.',
  },
  {
    rank: 68,
    name: 'Rock Island',
    locality: 'Siargao Island',
    country: 'Philippines',
    region: 'Southeast Asia',
    lat: 9.8167,
    lon: 126.0833,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Sep–Dec',
    description: 'A more forgiving alternative to Cloud 9, Rock Island is a fun right-hand reef break on Siargao that fires when Cloud 9 is too big or too crowded. The wave peels along a reef with good consistency and manageable power for advanced surfers seeking tube time. Its proximity to Cloud 9 makes it part of every Siargao itinerary, and the boat ride out adds to the adventure.',
  },
  {
    rank: 69,
    name: 'Lakey Peak',
    locality: 'Sumbawa',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -8.9667,
    lon: 118.6500,
    waveType: 'Beach Break',
    difficulty: 'Advanced',
    bestSeason: 'Jun–Sep',
    description: 'An A-frame beach break on the remote south coast of Sumbawa that delivers both left and right barrels simultaneously. Lakey Peak is the hub of a small cluster of world-class breaks — Lakey Pipe and Periscopes — that make Sumbawa one of Indonesia\'s premier destinations after Bali. The dry season offshore winds keep it clean and the beach camp scene keeps it social.',
  },
  {
    rank: 70,
    name: 'Supersuck',
    locality: 'Sumbawa',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -8.9833,
    lon: 118.6333,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Jun–Sep',
    description: 'A brutal, shallow reef break near Lakey Peak that lives up to its name by vacuuming water off the reef and creating pitching barrels of extraordinary violence. Supersuck is not for the faint-hearted — the reef is sharp, the drop is steep, and the wave throws with zero mercy. On the right day, it is one of the most intense surf experiences in Southeast Asia.',
  },
  {
    rank: 71,
    name: 'Nihiwatu',
    locality: 'Sumba Island',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -9.6667,
    lon: 119.0833,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Apr–Sep',
    description: 'A private reef break on the west coast of Sumba accessible only to guests of the legendary Nihiwatu resort. The wave — known as God\'s Left — is a long, cavernous left-hand barrel that fires on Indian Ocean swells in almost total isolation. Sumba\'s traditional culture, wild horses on the beach, and an absolute absence of crowds make this the most exclusive surf experience on earth.',
  },
  {
    rank: 72,
    name: 'Nusa Dua',
    locality: 'South Bali',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -8.8114,
    lon: 115.2295,
    waveType: 'Reef Break',
    difficulty: 'Intermediate',
    bestSeason: 'Apr–Oct',
    description: 'The right-hand reef on the southern tip of Bali\'s Nusa Dua peninsula offers long, workable walls for intermediate and advanced surfers on Indian Ocean swells. The adjacent Nusa Dua Hotel Zone hosts luxury resorts, but the wave itself is democratically accessible. The deeper reef and more forgiving shape make it the ideal step-up break after mastering Kuta\'s beach break.',
  },
  {
    rank: 73,
    name: 'Balian',
    locality: 'West Bali',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -8.3833,
    lon: 114.9000,
    waveType: 'River Mouth',
    difficulty: 'Intermediate',
    bestSeason: 'Apr–Oct',
    description: 'A mellow left-hand river mouth break on Bali\'s tranquil west coast that works year-round and provides a laid-back alternative to the Bukit\'s heavier reef breaks. Balian\'s longer, more forgiving walls are ideal for intermediate surfers building confidence, and the small village and bamboo warungs along the beach provide a slice of authentic Bali far from the tourist centres.',
  },
  {
    rank: 74,
    name: 'Bawa',
    locality: 'Siberut, Mentawai',
    country: 'Indonesia',
    region: 'Southeast Asia',
    lat: -1.3167,
    lon: 98.9000,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Apr–Oct',
    description: 'A seldom-surfed right-hand reef in the northern Mentawais that rewards liveaboards venturing off the standard circuit. Bawa can produce extraordinary barrels on the right swell — longer and rawer than its more famous southern counterparts. Its relative obscurity means that on the rare occasions it fires to perfection, you might surf it alone or with just a handful of other boats.',
  },

  // ── Oceania & Pacific ──────────────────────────────────────────────────────────
  {
    rank: 75,
    name: 'Teahupo\'o',
    locality: 'Tahiti',
    country: 'French Polynesia',
    region: 'Oceania & Pacific',
    lat: -17.8561,
    lon: -149.2578,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Apr–Sep',
    wslBadge: 'CT Stop',
    description: 'The heaviest wave on earth. Teahupo\'o breaks over a coral shelf so shallow that the water literally runs dry at the bottom of the barrel, producing waves that are thicker than they are tall. The CT event here — nicknamed the "Code Red" event — has produced the most spectacular and terrifying surfing imagery ever captured. Laird Hamilton\'s 2000 ride here redefined what was possible in surfing.',
  },
  {
    rank: 76,
    name: 'Cloudbreak',
    locality: 'Tavarua Island',
    country: 'Fiji',
    region: 'Oceania & Pacific',
    lat: -17.9667,
    lon: 177.2000,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Apr–Oct',
    wslBadge: 'CT Stop',
    description: 'One of the finest left-hand reef breaks in the world, Cloudbreak detonates on a horseshoe-shaped reef a mile offshore from Tavarua Island. At 6–10ft it delivers world-class surfing with multiple sections; at 15ft+ it becomes a legitimate big-wave arena. The 2012 Volcom Fiji Pro produced what many consider the greatest day of professional surfing ever photographed.',
  },
  {
    rank: 77,
    name: 'Restaurants',
    locality: 'Tavarua Island',
    country: 'Fiji',
    region: 'Oceania & Pacific',
    lat: -17.9833,
    lon: 177.1833,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Apr–Oct',
    description: 'The right-hand complement to Cloudbreak, Restaurants breaks on the inside of the Tavarua reef and offers a more accessible but still world-class experience. Long walls and shorter barrel sections make it forgiving enough for strong intermediate surfers while still delivering genuine tube rides. The Tavarua resort\'s boat service puts you in the lineup within minutes of waking up.',
  },
  {
    rank: 78,
    name: 'Namotu Left',
    locality: 'Namotu Island',
    country: 'Fiji',
    region: 'Oceania & Pacific',
    lat: -17.9500,
    lon: 177.1667,
    waveType: 'Reef Break',
    difficulty: 'Intermediate',
    bestSeason: 'Apr–Oct',
    description: 'A long, rolling left-hand reef break adjacent to the exclusive Namotu Island Resort that offers some of the best intermediate-level surfing in the South Pacific. Namotu Left provides long walls and easy tube sections in warm, clear Fijian water with an uncrowded lineup. On the right swell it connects for 200–300m — enough length to practice linking turns all the way to the channel.',
  },
  {
    rank: 79,
    name: 'Snapper Rocks',
    locality: 'Coolangatta, Gold Coast',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -28.1658,
    lon: 153.5517,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Mar–Sep',
    wslBadge: 'CT Stop',
    description: 'The start of the Gold Coast Superbank — a sandbars-and-rock-point system that can produce the longest rides in Australia. On cyclone-generated swells, Snapper connects through Greenmount to Kirra for 2km of barreling perfection. The Quiksilver Pro Gold Coast opens the CT season here and annually produces the highest heat scores in the tour calendar.',
  },
  {
    rank: 80,
    name: 'Kirra',
    locality: 'Gold Coast, Queensland',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -28.1736,
    lon: 153.5414,
    waveType: 'Point Break',
    difficulty: 'Expert',
    bestSeason: 'Mar–Sep',
    description: 'When the Superbank\'s sand connects, Kirra emerges as perhaps the most perfect and dangerous end section in world surfing. The barrel at Kirra is fast, shallow, and relentless — a tube that closes faster than any other break on the Superbank. Cyclone swells and the right sandbank configurations create Kirra sessions that legendary surfers speak of for decades.',
  },
  {
    rank: 81,
    name: 'Burleigh Heads',
    locality: 'Gold Coast, Queensland',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -28.0868,
    lon: 153.4583,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Mar–Sep',
    description: 'A legendary headland point break that has shaped Queensland surfing and produced some of Australia\'s finest competitive surfers. Burleigh wraps around a volcanic headland covered with Burleigh Heads National Park, delivering long rights that are powerful, fast, and rewarding for surfers who can ride at speed. The Burleigh Head section at the end of the point is one of the most barreling waves on the Gold Coast.',
  },
  {
    rank: 82,
    name: 'Bells Beach',
    locality: 'Torquay, Victoria',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -38.3700,
    lon: 144.2800,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Mar–Jul',
    wslBadge: 'CT Stop',
    description: 'The spiritual home of Australian surfing, Bells Beach has hosted the Rip Curl Pro continuously since 1961 — the longest-running professional surfing event in the world. The cold Southern Ocean delivers powerful, long-period groundswells that wrap into the amphitheatre-shaped cliff bowl. Bells is powerful, cold, and demanding — a test of surfing\'s deepest traditions.',
  },
  {
    rank: 83,
    name: 'Margaret River Main Break',
    locality: 'Western Australia',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -33.9500,
    lon: 114.9833,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Mar–Aug',
    wslBadge: 'CT Stop',
    description: 'The most powerful CT wave in Australia, Margaret River Main Break fires on direct Southern Ocean groundswells over a shallow reef on WA\'s wild coastline. The Margaret River Pro regularly produces the most dangerous conditions on the entire tour. The combination of power, cold water, and consistent swell makes the Margaret River region — a cluster of world-class reefs — Australia\'s most complete surf destination.',
  },
  {
    rank: 84,
    name: 'The Box',
    locality: 'Margaret River, Western Australia',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -33.9417,
    lon: 114.9833,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Mar–Aug',
    wslBadge: 'Big Wave',
    description: 'Adjacent to the Margaret River Main Break, The Box is a shallow, slab-type reef that only handles truly large Southern Ocean swells — and when it does, it produces some of the most violent, close-out barrels in Australia. Named for the square cross-section of its barrel, it\'s a wave that separates serious surfers from the rest. At 12ft+ it is beyond description.',
  },
  {
    rank: 85,
    name: 'Shipstern Bluff',
    locality: 'Tasmania',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -43.4000,
    lon: 146.9167,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Apr–Sep',
    wslBadge: 'Big Wave',
    description: 'Australia\'s most extreme big-wave break, Shipstern Bluff is a left-hand slab on Tasmania\'s remote southwest coast accessible only by sea. The wave features a mid-face ledge — the "step" — that interrupts the barrel and sends surfers airborne before the tube closes out with ferocious force. Cold water, great white sharks, and a 4km hike through ancient rainforest gatekeep the experience.',
  },
  {
    rank: 86,
    name: 'Noosa (First Point)',
    locality: 'Noosa, Queensland',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -26.3600,
    lon: 153.0933,
    waveType: 'Point Break',
    difficulty: 'Beginner',
    bestSeason: 'Mar–Aug',
    description: 'The finest longboard wave in Australia, Noosa\'s First Point delivers perfectly formed right-hand walls through a national park that protects the coastline from development. The Noosa Festival of Surfing celebrates everything from Mal log surfing to prone paddleboarding here annually. The warm, crystal-clear water and protected national park setting make it one of Queensland\'s most treasured surfing places.',
  },
  {
    rank: 87,
    name: 'Angourie',
    locality: 'Yamba, New South Wales',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -29.4667,
    lon: 153.3667,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Apr–Sep',
    description: 'One of NSW\'s most revered point breaks, Angourie is a long right-hander in a national park that delivers powerful, workable walls on consistent NE swells. The Blue Pool — a freshwater rock pool adjacent to the break — is as beloved by locals as the surf itself. On a solid 6ft swell, Angourie produces some of the most satisfying long-period rides on Australia\'s east coast.',
  },
  {
    rank: 88,
    name: 'North Narrabeen',
    locality: 'Sydney, New South Wales',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -33.7167,
    lon: 151.3000,
    waveType: 'Beach Break',
    difficulty: 'Intermediate',
    bestSeason: 'Mar–Aug',
    description: 'The most consistently good beach break in Sydney and one of Australia\'s most storied surf spots. North Narrabeen has produced multiple world champions and remains the spiritual home of Sydney\'s surfing culture. Its reliable beach break peaks work on a wide range of swell directions, and the local surf club tradition keeps the community tight-knit and the standards high.',
  },
  {
    rank: 89,
    name: 'Raglan',
    locality: 'Waikato',
    country: 'New Zealand',
    region: 'Oceania & Pacific',
    lat: -37.8000,
    lon: 174.8667,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Apr–Sep',
    description: 'New Zealand\'s most famous wave is a long left-hand point break on the Tasman Sea coast that has been delivering world-class rides since Barry Gifford first surfed it in the 1960s. Raglan\'s multiple sections — Manu Bay and Whale Bay — produce walls of up to 400 metres on the right SW groundswell. Cold, green, consistent, and surrounded by fern-covered New Zealand farmland.',
  },
  {
    rank: 90,
    name: 'Piha',
    locality: 'Waitakere Ranges, Auckland',
    country: 'New Zealand',
    region: 'Oceania & Pacific',
    lat: -36.9667,
    lon: 174.4667,
    waveType: 'Beach Break',
    difficulty: 'Advanced',
    bestSeason: 'Mar–Sep',
    description: 'New Zealand\'s most iconic beach, Piha sits in a valley of black sand at the foot of Lion Rock, protected by the Waitakere Ranges. The powerful Tasman Sea beach break is responsible for many of NZ\'s surf rescues — and its surf lifesaving culture is as strong as its surf. On the right swell it delivers punchy, powerful waves that rival anything on the NZ coast.',
  },
  {
    rank: 91,
    name: 'Whale Bay',
    locality: 'Raglan, Waikato',
    country: 'New Zealand',
    region: 'Oceania & Pacific',
    lat: -37.8167,
    lon: 174.8500,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Apr–Sep',
    description: 'The second section of the Raglan point system, Whale Bay receives larger, more exposed swell and produces longer, more powerful walls than Manu Bay. On a significant SW groundswell, it connects with Manu Bay for one of the longest rides in New Zealand. The uncrowded lineup, clean green water, and dramatic fern-clad cliffs make it one of the most beautiful surf spots in the Southern Hemisphere.',
  },
  {
    rank: 92,
    name: 'Taapuna',
    locality: 'Tahiti',
    country: 'French Polynesia',
    region: 'Oceania & Pacific',
    lat: -17.6500,
    lon: -149.8333,
    waveType: 'Reef Break',
    difficulty: 'Advanced',
    bestSeason: 'Apr–Sep',
    description: 'The more accessible sibling of Teahupo\'o, Taapuna is a quality right-hand reef break on Tahiti\'s west coast that delivers powerful, hollow waves without the extreme shallow-water danger of the more famous break. It serves as the "local\'s wave" for Papeete surfers and provides an excellent alternative for advanced surfers who want a taste of Polynesian reef surfing at a more manageable consequence level.',
  },
  {
    rank: 93,
    name: 'Wilkes Pass',
    locality: 'Tavarua Island',
    country: 'Fiji',
    region: 'Oceania & Pacific',
    lat: -17.9500,
    lon: 177.1500,
    waveType: 'Reef Break',
    difficulty: 'Intermediate',
    bestSeason: 'Apr–Oct',
    description: 'A right-hand reef pass in the Tavarua cluster that works on smaller swells when Cloudbreak is too powerful. Wilkes Pass provides a more relaxed alternative with fun, consistent walls and shorter barrel sections. The Tavarua surf camp uses it as the go-to when conditions suit intermediate surfers, and its warm Fijian water and accessible channel make it one of the most pleasant surf experiences in the Pacific.',
  },
  {
    rank: 94,
    name: 'Gnaraloo',
    locality: 'Carnarvon, Western Australia',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -23.8333,
    lon: 113.5167,
    waveType: 'Point Break',
    difficulty: 'Expert',
    bestSeason: 'Apr–Sep',
    description: 'A remote right-hand point break on WA\'s Coral Coast that delivers long, powerful rides on Southern Ocean groundswells in a wilderness setting accessible only by long dirt track. Gnaraloo\'s Tombstones section is a genuine slab that breaks over a shallow reef with ferocity. The station homestead provides simple accommodation; otherwise, it\'s camping under stars, surfing alone, and watching humpback whales breach offshore.',
  },
  {
    rank: 95,
    name: 'The Right',
    locality: 'Augusta, Western Australia',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -34.9667,
    lon: 117.4167,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Mar–Aug',
    wslBadge: 'Big Wave',
    description: 'A frightening big-wave right-hander near Augusta in WA that is widely considered the most dangerous wave in Australia. The Right detonates on a submerged reef with immense power, creating a thick, barreling lip that has broken boards, ribs, and surfers. Cold Southern Ocean water, white sharks, and the sheer violence of the wave restrict sessions to the most committed big-wave surfers in Australia.',
  },
  {
    rank: 96,
    name: 'Cronulla Point',
    locality: 'Sydney, New South Wales',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -34.0517,
    lon: 151.1567,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Mar–Aug',
    description: 'Sydney\'s southernmost surf community is built around a rocky headland point that wraps NE and SE swells into a classic right-hand wall. Cronulla Point is a surfers\' surfer\'s wave — powerful, consistent, and demanding — that has produced world-class talent from a city-fringe suburb. The local crew is one of the most passionate and tight-knit surf communities in Australia.',
  },
  {
    rank: 97,
    name: 'Lennox Head',
    locality: 'Northern Rivers, New South Wales',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -28.8000,
    lon: 153.5833,
    waveType: 'Point Break',
    difficulty: 'Advanced',
    bestSeason: 'Mar–Sep',
    description: 'A long right-hand point on NSW\'s northern coast that consistently rates among the top five point breaks in Australia. Lennox Head delivers rides of 200–400m on cyclone-generated east swells, with a powerful, fast-walling section over the rocky bottom. The headland is protected and the town retains its surf village character — a welcome contrast to the Gold Coast\'s commercial sprawl just over the border.',
  },
  {
    rank: 98,
    name: 'Superbank (full run)',
    locality: 'Coolangatta–Kirra, Gold Coast',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -28.1700,
    lon: 153.5450,
    waveType: 'Sand Bar',
    difficulty: 'Expert',
    bestSeason: 'Mar–Jun',
    description: 'When cyclone-generated swells hit the Gold Coast at the right angle and the sand connects from Snapper Rocks through Greenmount and Rainbow Bay all the way to Kirra, the result is a 2-kilometre barreling conveyor belt with no equal on earth. The full Superbank connection only happens a handful of times per year, but when it does, it is one of surfing\'s most extraordinary events.',
  },
  {
    rank: 99,
    name: 'Black Rock',
    locality: 'Phillip Island, Victoria',
    country: 'Australia',
    region: 'Oceania & Pacific',
    lat: -38.4914,
    lon: 145.1803,
    waveType: 'Reef Break',
    difficulty: 'Expert',
    bestSeason: 'Apr–Sep',
    description: 'A powerful, hollow left-hand reef break on Phillip Island\'s exposed southern coastline that fires on Bass Strait groundswells in spectacular fashion. Black Rock is Victoria\'s most dramatic wave — a thick, pitching barrel that breaks over a shallow basalt reef with cold Southern Ocean water and wild winds. The backdrop of penguins, seals, and crashing seas makes every session memorable.',
  },
  {
    rank: 100,
    name: 'Sanur Reef',
    locality: 'Sanur, Bali',
    country: 'Indonesia',
    region: 'Oceania & Pacific',
    lat: -8.7000,
    lon: 115.2700,
    waveType: 'Reef Break',
    difficulty: 'Intermediate',
    bestSeason: 'Apr–Oct',
    description: 'A long right-hand reef break off Sanur\'s calm east coast beach that works on the same Indian Ocean swells as the Bukit but with a gentler character. Sanur Reef is Bali\'s hidden gem for intermediate and advanced surfers seeking quality waves without the Bukit\'s crowds and consequence. The reef break delivers long, consistent walls with good shape — ideal for progressing surfers ready to move from beach to reef.',
  },
]
